<a href="https://colab.research.google.com/github/sayalivadya1654-cell/Car-Resale-Price-Prediction/blob/main/Car_Resale_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# import required libaries
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [27]:
# load dataset
df = pd.read_csv("/content/used_cars_dataset.csv")

In [26]:
df.shape

(1050, 14)

In [29]:
df.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Nissan Terrano XV,Hyderabad,2007,127225,Diesel,Automatic,Second,24.16 kmpl,1561 CC,131.39 bhp,7.0,41.3 Lakh,10.89
1,1,Hyundai i20 Sportz,Pune,2010,102800,Diesel,Automatic,First,19.29 kmpl,1973 CC,204.57 bhp,5.0,NaN,18.96
2,2,Skoda Yeti Ambition,Delhi,2006,120317,Diesel,Manual,First,19.3 kmpl,2186 CC,175.17 bhp,7.0,63.11 Lakh,15.79
3,3,Audi Q3 2.0 TDI,Hyderabad,2015,49027,Diesel,Automatic,First,18.88 kmpl,1812 CC,203.29 bhp,7.0,98.2 Lakh,63.75
4,4,Hyundai i10 Magna,Pune,2007,207392,Diesel,Automatic,First,25.22 kmpl,1181 CC,89.93 bhp,7.0,30.37 Lakh,8.83

In [30]:
df.tail()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
1045,1045,Hyundai i20 Sportz,Bangalore,2011,76927,Diesel,Manual,Second,26.88 kmpl,1100 CC,96.23 bhp,5.0,33.28 Lakh,12.75
1046,1046,Honda BR-V VX i-DTEC,Coimbatore,2014,86847,Diesel,Automatic,First,24.53 kmpl,1523 CC,114.39 bhp,7.0,38.73 Lakh,20.52
1047,1047,Ford Endeavour Titanium,Bangalore,2015,43170,Diesel,Automatic,Second,24.43 kmpl,1364 CC,119.15 bhp,7.0,35.18 Lakh,18.99
1048,1048,Hyundai i20 Sportz,Mumbai,2008,136828,Petrol,Manual,Third,24.74 kmpl,1288 CC,97.69 bhp,7.0,NaN,7.08
1049,1049,Maruti Alto 800 LXI,Ahmedabad,2005,109477,Diesel,Manual,Second,25.8 kmpl,925 CC,93.91 bhp,5.0,NaN,6.96

In [32]:
df.columns

Index(['S.No.', 'Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price', 'Price'],
      dtype='object')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              1050 non-null   int64
 1   Name               1050 non-null   object
 2   Location           1050 non-null   object
 3   Year               1050 non-null   int64
 4   Kilometers_Driven  1050 non-null   int64
 5   Fuel_Type          1050 non-null   object
 6   Transmission       1050 non-null   object
 7   Owner_Type         1050 non-null   object
 8   Mileage            1050 non-null   object
 9   Engine             1050 non-null   object
 10  Power              1050 non-null   object
 11  Seats              1050 non-null   float64
 12  New_Price          684 non-null    object
 13  Price              1050 non-null   float64
dtypes: float64(2), int64(3), object(9)
memory usage: 115.0+ KB

In [33]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.isnull().sum()

S.No.                  0
Name                   0
Location               0
Year                   0
Kilometers_Driven      0
Fuel_Type              0
Transmission           0
Owner_Type             0
Mileage                0
Engine                 0
Power                  0
Seats                  0
New_Price            366
Price                  0
dtype: int64

In [35]:
df = df.drop(columns=["New_Price"])

In [36]:
df.shape

(1050, 13)

In [37]:
df = df.drop(columns=["S.No."])

In [38]:
df.shape

(1050, 12)

In [46]:
# conver mileage
df['Mileage'] = df['Mileage'].astype(str).str.split().str[0].astype(float)

In [47]:
# convert engine
df['Engine'] = df['Engine'].astype(str).str.split().str[0].astype(float)

In [48]:
# convert power
df['Power'] = df['Power'].astype(str).str.split().str[0].astype(float)